export const PATHS = {
  ROOT: '/',
  AUTH: {
    LOGIN: '/auth/login',
    VERIFY_OTP: '/auth/login/verify-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    SET_PASSWORD: '/user/set-password',
  },
  ERROR: {
    UNAUTHORIZED: '/unauthorized',
  },
  ADMIN: {
    DASHBOARD: '/',
    PROFILE: 'accounts/profile',
    USERS: {
      BASE: 'admin/users',
      DETAILS: 'admin/users/user-details',
      DETAIL: 'admin/users/user-details/:id',
      COUNTRY_ANALYSIS: 'admin/users/countrywise-Analysis',
      COUNTRY_DETAIL: 'admin/users/countrywise-Analysis/:id',
      REPORTED: 'admin/users/reported-user-list',
      STAFF_DETAIL: 'admin/users/:id',
    },
    GROUPS: {
      LIST: 'admin/Group/all-group-list',
      DETAIL: 'admin/Group/all-group-list/:id',
      REPORTED: 'admin/Group/all-reported-group-list',
    },
    SYSTEM: {
      ROLES: {
        LIST: 'admin/system/roles',
        DETAIL: 'admin/system/roles/:id',
        CREATE: 'admin/system/roles/create',
        EDIT: 'admin/system/roles/:id/edit',
      },
      USERS: 'admin/system/users',
      NOTIFICATIONS: {
        BROADCASTS: 'admin/system/notifications/broadcasts',
      },
    },
    LIVESTREAMS: {
      ALL: 'admin/livestreams/all-livestreams',
      SCHEDULED: 'admin/livestreams/scheduled',
      SETTINGS: 'admin/livestreams/settings',
      CATEGORIES: 'admin/livestreams/categories',
      FEATURED: 'admin/livestreams/featured',
      ANALYTICS: 'admin/livestreams/analytics',
      MODERATION: 'admin/livestreams/moderation',
      REPORTED: 'admin/livestreams/reported',
    },
    FINANCE: {
      FOREX: {
        DASHBOARD: 'admin/finance/forex/dashboard',
        CURRENCIES: 'admin/finance/forex/currencies',
        CURRENCY_PAIRS: 'admin/finance/forex/currency-pairs',
        EXCHANGE_RATES: 'admin/finance/forex/exchange-rates',
        ALERTS: 'admin/finance/forex/alerts',
        SETTINGS: 'admin/finance/forex/settings',
      },
      TRANSACTIONS: {
        LIST: 'admin/finance/transactions',
        RECEIPT: 'admin/finance/transactions/receipt/:id',
      },
      FEE_RULES: {
        LIST: 'admin/finance/fee-rules',
        EDIT: 'admin/finance/fee-rules/edit/:id',
        ADD: 'admin/finance/fee-rules/add',
      },
      LIMITS: {
        LIST: 'admin/finance/limits',
        ADD: 'admin/finance/limits/add',
        EDIT: 'admin/finance/limits/edit/:id',
        VERIFICATION: 'admin/finance/limits/verification',
      },
      COMPLIANCE: {
        LIST: 'admin/finance/compliance',
        RULE: 'admin/finance/compliance/rules/:id',
      },
      WALLETS: {
        SYSTEM: 'admin/finance/wallets',
        REVERSAL_REQUESTS: 'admin/finance/wallets/reversal-requests',
        REVERSAL_DETAIL: 'admin/finance/wallets/reversal-requests/:id',
        USER: 'admin/finance/user-wallets',
        USER_DETAIL: 'admin/finance/user-wallets/:id',
      },
      BANKS: 'admin/finance/banks',
      WITHDRAWALS: 'admin/finance/withdrawals',
      TOP_UPS: 'admin/finance/top-ups',
      PAYMENT_METHODS: 'admin/finance/payment-methods',
      REPORTS: 'admin/finance/reports',
      GIFT_HISTORY: 'admin/finance/gift-history',
    },
    WALLPAPER: {
      LIST: 'admin/Wallpaper/list-all-wallpaper',
      ADD: 'admin/Wallpaper/add-a-new-wallpaper',
    },
    AVATAR: {
      LIST: 'admin/Avatar/list-all-avatar',
      ADD: 'admin/Avatar/add-a-new-avatar',
    },
    SETTINGS: {
      GENERAL: 'admin/settings',
      EMOJI: 'admin/emojis',
      LANGUAGES: {
        LIST: 'admin/languages',
        TRANSLATIONS: 'admin/languages/:id/translations',
      },
    },
    CHAT: {
      MODERATION: 'admin/chats/moderation',
    },
    GIFTS: {
      LIST: 'admin/gifts/gift-list',
      ADD: 'admin/gifts/add-gift',
      CATEGORIES: 'admin/gifts/gift-categories',
    },
    MEDIA: {
      SHORTS: {
        DASHBOARD: 'admin/media/shorts',
        MODERATION: 'admin/media/shorts/moderation',
        MODERATION_DETAIL: 'admin/media/shorts/moderation/:videoId',
        REPORTS: 'admin/media/shorts/reports',
        REPORT_DETAIL: 'admin/media/shorts/reports/:reportId',
        COMMENTS: 'admin/media/shorts/comments',
        COMMENTS_VIDEO: 'admin/media/shorts/comments/:videoId',
        HASHTAGS: 'admin/media/shorts/hashtags',
        HASHTAGS_BLOCKED: 'admin/media/shorts/hashtags/blocked',
        HASHTAGS_TRENDING: 'admin/media/shorts/hashtags/trending',
        CREATORS: 'admin/media/shorts/creators',
        CREATOR_DETAIL: 'admin/media/shorts/creators/:creatorId',
        PROMOTION: 'admin/media/shorts/promotion',
        PROMOTION_TRENDING: 'admin/media/shorts/promotion/trending',
        PROMOTION_FEATURED: 'admin/media/shorts/promotion/featured',
        ANALYTICS: 'admin/media/shorts/analytics',
        ANALYTICS_VIDEOS: 'admin/media/shorts/analytics/videos',
        ANALYTICS_MODERATION: 'admin/media/shorts/analytics/moderation',
        NOTIFICATIONS: 'admin/media/shorts/notifications',
        NOTIFICATIONS_TEMPLATES: 'admin/media/shorts/notifications/templates',
        NOTIFICATION_DETAIL: 'admin/media/shorts/notifications/templates/:id',
        SETTINGS: 'admin/media/shorts/settings',
      },
    },
    COMMUNICATION: {
      BROADCASTS: {
        ADD: 'admin/communication/broadcasts/add',
        EDIT: 'admin/communication/broadcasts/edit/:id',
      },
    },
    SUPPORT: {
      DASHBOARD: 'admin/support/dashboard',
      TICKETS: 'admin/support/tickets',
      TICKET_DETAIL: 'admin/support/tickets/:id',
      NEW_TICKET: 'admin/support/tickets/new',
      SLA_LIST: 'admin/support/sla',
      SLA_DETAIL: 'admin/support/sla/:id',
      SLA_CREATE: 'admin/support/sla/create',
      SLA_EDIT: 'admin/support/sla/:id/edit',
      CATEGORIES: 'admin/support/categories',
      CATEGORY_DETAIL: 'admin/support/categories/:id',
      CATEGORY_CREATE: 'admin/support/categories/create',
      CATEGORY_EDIT: 'admin/support/categories/:id/edit',
      STATISTICS: 'admin/support/statistics',
    },
    AUDITS: {
      LOGS: 'admin/logs',
      DETAILS: 'admin/audit-logs/:id',
    },
  },
};
